name: Run Jest Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: 🔧 Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 依存パッケージをインストール
        run: npm install

      - name: 🧪 Jest テストを実行
        run: npm test
